spring:
  application:
    name: account-movement-authorizer
  profiles:
    default: local
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/account_authorizer
    username: account_authorizer
    password: account_authorizer
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        format_sql: false

server:
  port: 0
